//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public int EmailID { get; set; }
        public string RecipientType { get; set; }
        public int RecipientID { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string EmailType { get; set; }
        public System.DateTime SentAt { get; set; }
    }
}
