//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceDB1Entities : DbContext
    {
        public InsuranceDB1Entities()
            : base("name=InsuranceDB1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<ClientPayment> ClientPayments { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Conversation> Conversations { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<EmailLog> EmailLogs { get; set; }
        public virtual DbSet<LoginCredential> LoginCredentials { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<PolicyApproval> PolicyApprovals { get; set; }
        public virtual DbSet<PolicyDueDate> PolicyDueDates { get; set; }
        public virtual DbSet<PolicyType> PolicyTypes { get; set; }
        public virtual DbSet<PremiumCalculation> PremiumCalculations { get; set; }
        public virtual DbSet<Renewal> Renewals { get; set; }
        public virtual DbSet<TravelDetail> TravelDetails { get; set; }
        public virtual DbSet<UserPolicy> UserPolicies { get; set; }
        public virtual DbSet<UserPolicyApproval> UserPolicyApprovals { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VehicleDetail> VehicleDetails { get; set; }
    }
}
