//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumCalculation
    {
        public int CalculationID { get; set; }
        public int UserID { get; set; }
        public int PolicyTypeID { get; set; }
        public string VehicleModel { get; set; }
        public Nullable<int> VehicleAge { get; set; }
        public string TravelDetails { get; set; }
        public decimal EstimatedPremium { get; set; }
        public System.DateTime CalculatedAt { get; set; }
    
        public virtual PolicyType PolicyType { get; set; }
        public virtual User User { get; set; }
    }
}
