//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renewal
    {
        public int RenewalID { get; set; }
        public int UserPolicyID { get; set; }
        public System.DateTime RequestedAt { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
    
        public virtual UserPolicy UserPolicy { get; set; }
    }
}
