//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentID { get; set; }
        public string OwnerType { get; set; }
        public int OwnerID { get; set; }
        public string DocumentType { get; set; }
        public string FilePath { get; set; }
        public System.DateTime UploadedAt { get; set; }
        public bool IsVerified { get; set; }
        public string VerifiedByRole { get; set; }
        public Nullable<int> VerifiedByID { get; set; }
        public Nullable<System.DateTime> VerifiedAt { get; set; }
        public string Visibility { get; set; }
        public string FileName { get; internal set; }
        public DateTime CreatedAt { get; internal set; }
    }
}
