//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public int ConversationID { get; set; }
        public string SenderRole { get; set; }

        public int SenderID { get; set; }
        public string Body { get; set; }
        public System.DateTime SentAt { get; set; }
    
        public virtual Conversation Conversation { get; set; }

    }
}
