//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyApproval
    {
        public int ApprovalID { get; set; }
        public int PolicyID { get; set; }
        public int AdminID { get; set; }
        public string Decision { get; set; }
        public System.DateTime DecisionAt { get; set; }
        public string Notes { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Policy Policy { get; set; }
    }
}
