//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPolicyApproval
    {
        public int UserPolicyApprovalID { get; set; }
        public int UserPolicyID { get; set; }
        public int ClientID { get; set; }
        public string Decision { get; set; }
        public System.DateTime DecisionAt { get; set; }
        public string Notes { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual UserPolicy UserPolicy { get; set; }
    }
}
