//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail
    {
        public int VehicleDetailsID { get; set; }
        public int UserPolicyID { get; set; }
        public string VehicleType { get; set; }
        public string VehicleName { get; set; }
        public string Model { get; set; }
        public string DrivingLicense { get; set; }
        public string RegistrationNumber { get; set; }
        public string RCNumber { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string EngineNumber { get; set; }
        public string ChassisNumber { get; set; }
        public string HolderName { get; set; }
    
        public virtual UserPolicy UserPolicy { get; set; }
    }
}
