//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPayment
    {
        public int ClientPaymentID { get; set; }
        public int ClientID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaidAt { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
