//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyDueDate
    {
        public int DueDateID { get; set; }
        public int UserPolicyID { get; set; }
        public System.DateTime DueDate { get; set; }
        public bool IsPaid { get; set; }
        public bool ReminderSent { get; set; }
    
        public virtual UserPolicy UserPolicy { get; set; }
    }
}
