//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelDetail
    {
        public int TravelDetailsID { get; set; }
        public int UserPolicyID { get; set; }
        public string PersonName { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string HealthIssues { get; set; }
    
        public virtual UserPolicy UserPolicy { get; set; }
    }
}
